name: Checkstyle

on: [push, pull_request]

jobs:
  build:
    name: Checkstyle ${{ matrix.java-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 18
          cache: maven
      - name: Set Maven Wrapper
        run: mvn wrapper:wrapper -Dmaven=3.8.4
      - name: Checkstyle
        run: ./mvnw site
      - name: Archive reports
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-reports
          path: target/site/**/*
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'
