name: Unit tests

on: [push, pull_request]

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 18
          cache: maven
      - name: Setup libsodium
        run: sudo apt-get install -y libsodium-dev
      - name: Symlink libsodium
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libsodium.so /usr/lib64/libsodium.so.23
      - name: Set Maven Wrapper
        run: mvn wrapper:wrapper -Dmaven=3.8.4
      - name: Unit-Test
        run: ./mvnw clean verify --no-transfer-progress
      - name: Archive JaCoCo reports
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target/*.jar
